workflows:
  ios-ipa:
    name: iOS Unsigned IPA Build

    instance_type: mac_mini_m2

    environment:
      flutter: stable

      vars:
        GOOGLE_CLIENT_ID: "1051124848059-7guhimh3iuf97knav7oi9ofbsok6fagj.apps.googleusercontent.com"
        GOOGLE_SERVER_CLIENT_ID: "1051124848059-c1si7f3i0njmhm2baeit8oacri1cin19.apps.googleusercontent.com"
        API_BASE_URL: "https://sync.vidyashilp.edu.in"

    scripts:
      - name: Flutter pub get
        script: |
          cd mobile_app
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd mobile_app/ios
          pod install

      - name: Build unsigned IPA
        script: |
          cd mobile_app
          flutter build ipa --release --no-codesign \
            --dart-define=GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
            --dart-define=GOOGLE_SERVER_CLIENT_ID=$GOOGLE_SERVER_CLIENT_ID \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - mobile_app/build/ios/ipa/*.ipa